### ISSUE TITLE
Unable to start slimserver on MaxOS 13.0 (Ventura)

### ISSUE THREAD

**Issue by darylfoster** [LMS-Community/slimserver-vendor#100]
I normally start slimserver via the command line: `perl /Library/PreferencePanes/Squeezebox.prefPane/Contents/server/slimserver.pl`

After upgrading to Ventura, I get the following:

The following modules failed to load: EV

This is perl 5, version 30, subversion 3 (v5.30.3) built for darwin-thread-multi-2level
(with 2 registered patches, see perl -V for more detail)

Copyright 1987-2020, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

*******

NOTE:

If you're running some unsupported Linux/Unix platform, please use the buildme.sh
script located here:

https://github.com/Logitech/slimserver-vendor/tree/public/8.2/CPAN

If 8.2 is outdated by the time you read this, Replace "8.2" with the major version
You should never need to do this if you're on Windows or Mac OSX. If the installers
don't work for you, ask for help and/or report a bug.

*******

			
Exiting..
Can't locate Tie/Cache/LRU.pm in @INC (you may need to install the Tie::Cache::LRU module) (@INC contains: /Library/Application Support/Squeezebox /Users/daddy/Library/Application Support/Squeezebox /Library/PreferencePanes/Squeezebox.prefPane/Contents/server /Library/Perl/5.30/darwin-thread-multi-2level /Library/Perl/5.30 /Network/Library/Perl/5.30/darwin-thread-multi-2level /Network/Library/Perl/5.30 /Library/Perl/Updates/5.30.3 /System/Library/Perl/5.30/darwin-thread-multi-2level /System/Library/Perl/5.30 /System/Library/Perl/Extras/5.30/darwin-thread-multi-2level /System/Library/Perl/Extras/5.30) at /Library/PreferencePanes/Squeezebox.prefPane/Contents/server/Slim/Utils/OS/OSX.pm line 346.
INIT failed--call queue aborted at /Library/PreferencePanes/Squeezebox.prefPane/Contents/server/slimserver.pl line 178.

**Comment by mherger** [comment]
Please download the latest 8.3 nightly build from https://downloads.slimdevices.com/nightly/?ver=8.3. macOS Ventura has dropped the Perl version we were relying on for many years.

**Comment by darylfoster** [comment]
Installing the 8.3 nightly build worked! Slimserver is now running on my MacOS 13.0 machine. I can also run Squeezelite on the same MacOS machine. However, my other devices are unable to connect to the slimserver.

I can access the Logitech Media Server web interface on the mac, but I cannot access it from other machines and devices on my network.

**Comment by mherger** [comment]
Check the Mac's firewall settings to make sure it allows access to LMS. You might have to grant the new Perl version full access to the disk, too.

**Comment by darylfoster** [comment]
Ok, I got it working by starting slimserver from the command line and specifying the perl version as follows:
`perl5.34 /Library/PreferencePanes/Squeezebox.prefPane/Contents/server/slimserver.pl`

That may not be the best solution, but it works! Thank you for your help.
