### ISSUE TITLE
Rsync moves to i386-linux folder and not i686-linux

### ISSUE THREAD

**Issue by jamesarbrown** [LMS-Community/slimserver-vendor#2]
This command for the rsync at the bottom of buildme.sh

ARCH=`$PERL_514 -MConfig -le 'print $Config{archname}' | sed 's/gnu-//' | sed 's/^i[3456]86-/i386-/' | sed 's/armv5tejl/arm/'` 

Particularly the sed 's/^i[345]86-/i386-/'

Changes the i686 to i368 resulting in a i386-linux folder instead of a i686-linux. As perl -v says compiled for i686-linux it ignores the i386-linux folder for libraries.

So even when forcing a perl -I eg
/opt/Perl5.14/bin/perl -I /opt/slimserver-vendor/CPAN/build/arch/5.14 /opt/slimserver/slimserver.pl

it can not find the built libraries. A symlink i686-linux to i386 fixed it

Fedora 18 i686

**Comment by chincheta0815** [comment]
Did not see that I have an open issue. How can I close this?
