### ISSUE TITLE
xlocale.h patch causes problem in Freenas 11.1

### ISSUE THREAD

**Issue by heank** [LMS-Community/slimserver-vendor#57]
When installing on FreeNAS 11.1, I had to comment out the following line since it was not able to find the strtod_l. I believe that function is defined in this xlocale.h. Commenting out the patch fixed my problem.
# Need to patch ICU to adapt to removal of xlocale.h on some platforms.
#patch -p0 < ../../icu58_patches/digitlst.cpp.patch

Also, I was unable to use perl5.26. I only got stuff working with perl5.24.1

**Comment by fsbruva** [comment]
Can you please try: fsbruva@7ef5559 and report back? That is one of the bugfixes in that set of commits.

**Comment by fsbruva** [comment]
@heank - Did you get a chance to test my patched fork?

**Comment by michaelherger** [comment]
I think I just run into this issue trying to build an up-to-date DBD::SQLite on macOS. Giving your changes a try now, @fsbruva .

**Comment by heank** [comment]
@fsbruva sorry for not responding to your questions. I had just spent days getting things working and needed to get a bit of a break. So, 1.5 yrs down, i broke my installation and redid everything with the latests versions. No problems encountered! I'm using Freenas 11.3, perl5.30.2, server version 7.9.2 (used the following tutorial (need to update the versionnumbers https://forums.slimdevices.com/showthread.php?104122-How-to-Installing-LMS-7-9-nightly-in-a-FreeBSD-jail-on-FreeNAS-9-3)
Eventhough it might be a bit late: thanks for fixing this issue :)
