### ISSUE TITLE
Question: Can I send a patch for buildme.sh changing removing "verbose" option from cp args?

### ISSUE THREAD

**Issue by chincheta0815** [LMS-Community/slimserver-vendor#76]
I recently found that buildme.sh causes less trouble on my system (OpenIndiana) when I simply remove the verbose option from the line in buildme.sh where cp is used. Since OpenIndiana's/Solaris' standard cp does not know the "verbose" option for cp there will be a lot of issues.

The reason for that change:
Illumos based systems do use their own ld as a default. When adding the dir containing the gnu tools and thus the gnu cp (knowing verbose), the build process also uses gnu ld. Gnu ld cuases build errors...

To avoid that the solution is simply removing the "verbose" option ("-v") from all cp calls in buildme.sh.

I would provide a PR, no problem. But before I would ask I there is any chance it will be accepted. And how you like it best:
- Simply remove all "-v" (least changes to the code),
- if statement what cp line to use (does not seem useful to me as it will increase complexity),
- remove all "-v" and add an echo telling what will be copied (in my opinion not really necessary, as a message ist sent when the cp fails).

I hope I get a go for my favorite (simply removing the "-v")

Thanks in advance.

**Comment by mherger** [comment]
Reviewing the code I see that the use of the `-v` flag is rather inconsistent. Feel free to remove it.

**Comment by chincheta0815** [comment]
Patch sent as PR #77
