### ISSUE TITLE
Question: FreeBSD 11.X and FreeBSD 12.X

### ISSUE THREAD

**Issue by cookiemonsteruk** [LMS-Community/slimserver-vendor#80]
Apologies if it is a dumb question but buildme.sh has freebsd documented OS and perl version documented up to 9: FreeBSD 8.X,9.X (Perl 5.12.4).
In order to build for freeBSD version 11.X or 12.X, which highest perl version do we need to test a build please?

**Comment by mherger** [comment]
I have no idea what exactly you're asking for. If you search issues and pull requests for freebsd, you should find some stuff (and names) around id in the closed tickets.

**Comment by cookiemonsteruk** [comment]
Ok Michael I could have been clearer. From your advice a search for pull requests for freebsd shows as latest, the commit #17 adds support for perl 5.26 and above on freebsdv11.X-amd64. This was a while ago but it helps.
The question was therefore: what is the current min and max perl version that we can build for freebsd, and what version of freebsd are supported.?
By the way I am not asking on behalf of a group, I'm trying to assist someone trying to build on freebsd 12.X and only perl 5.28 is available or higher.

**Comment by mherger** [comment]
No FreeBSD is supported out of the box. You'll have to compile binaries yourself. But I believe one of the guys had some recipe somewhere (I don't even know how FreeBSD manages applications...). But overall it should be compatible with at least Perl 5.30.

**Comment by cookiemonsteruk** [comment]
Brilliant, that is really helpful. Thanks Michael. I can work with that.
