### ISSUE TITLE
CPAN step-up to 8.2 ?

### ISSUE THREAD

**Issue by klslz** [LMS-Community/slimserver-vendor#82]
Since LMS is on 8.2 now, would be nice to step up CPAN accordingly.

Thx.

**Comment by zhellmann** [comment]
Please update repository to 8.2 as LMS 8.2 is not working on i686 & Perl 5.32.1 and the latest working repository is 8.0.

> If you're running some unsupported Linux/Unix platform, please use the buildme.sh
> script located here:
> 
> https://github.com/Logitech/slimserver-vendor/tree/public/8.2/CPAN
> 
> If 8.2 is outdated by the time you read this, Replace "8.2" with the major version
> You should never need to do this if you're on Windows or Mac OSX. If the installers
> don't work for you, ask for help and/or report a bug.
