### ISSUE TITLE
is branch 8.0 suitable for 8.1 builds?

### ISSUE THREAD

**Issue by pssc** [LMS-Community/slimserver-vendor#84]
Hi I am doing my own module build for a custom Conianter and running into issues and  I wanted to check?

**Comment by mherger** [comment]
Could you please be more specific? 8.0 branch in this repo to build 8.1 of LMS? Yes, that should be good. It's the latest we currently have.

**Comment by pssc** [comment]
Hi, yes trying to do a rebuild off the perl modules having oddities new installs don't work, existing ones do I am still digging.  Just wanted to check the 8.0 was ok.

**Comment by pssc** [comment]
I dont seem to get the same results as what is included in the debs for example

**Comment by pssc** [comment]
All though the layout isn't the same I can confirm it works on aarch64, amd64, i386, armv7 and armhf
