### ISSUE TITLE
Ubuntu 22.04 can't build slimserver-vendor-public-8.3

### ISSUE THREAD

**Issue by DaveInRedmond** [LMS-Community/slimserver-vendor#98]
Running the version installed from Ubuntu 20.04 after the upgrade generates:
Aug 16 13:40:58 WhiteCat squeezeboxserver[294954]: If you're running some unsupported Linux/Unix platform, please use the buildme.sh
Aug 16 13:40:58 WhiteCat squeezeboxserver[294954]: script located here:
Aug 16 13:40:58 WhiteCat squeezeboxserver[294954]: https://github.com/Logitech/slimserver-vendor/tree/public/8.3/CPAN
Aug 16 13:40:58 WhiteCat squeezeboxserver[294954]: If 8.3 is outdated by the time you read this, Replace "8.3" with the major version
Aug 16 13:40:58 WhiteCat squeezeboxserver[294954]: You should never need to do this if you're on Windows or Mac OSX. If the installers
Aug 16 13:40:58 WhiteCat squeezeboxserver[294954]: don't work for you, ask for help and/or report a bug.
Aug 16 13:40:58 WhiteCat squeezeboxserver[294954]: *******
Aug 16 13:40:58 WhiteCat squeezeboxserver[294954]:                         
Aug 16 13:40:58 WhiteCat squeezeboxserver[294954]: Exiting..
Aug 16 13:40:58 WhiteCat systemd[1]: logitechmediaserver.service: Deactivated successfully.
-----------------------
Executing buildme.sh with all files d/l from github generates:
Building for Linux / x86_64-linux-thread-multi
Building with Perl 5.34 at /usr/bin/perl
build_module run tests:0 clean:1 hints 1 Sub-Uplevel-0.22 
ERROR: cannot find source code archive Sub-Uplevel-0.22.tar.gz
Please download all source files from http://github.com/Logitech/slimserver-vendor

I receive the same error using files from slimserver-public-8.3/ or slimserver-vendor-public-8.3/

Any help/suggestions greatly appreciated.
Dave

**Comment by mherger** [comment]
The latest LMS 8.3 should have support for x86_64/Perl 5.34. What build ar eyou using? Would you mind sharing your full server.log.zip?

**Comment by DaveInRedmond** [comment]
On Wednesday, August 24, 2022 11:17:11 P.M. PDT Michael Herger wrote:
> The latest LMS 8.3 should have support for x86_64/Perl 5.34. What build ar
> eyou using? Would you mind sharing your full server.log.zip?

- I'm using perl v5.34.0
- the latest server log with any data is attached
- minor change - The OS was originally plain Ubuntu but I then switched to 
KDE. Shouldn't have an effect, but....

**Comment by mherger** [comment]
What would `ldd --version` give you?

**Comment by DaveInRedmond** [comment]
On Thursday, August 25, 2022 8:23:10 A.M. 
PDT Michael Herger wrote:
> ldd --version
ldd (Ubuntu GLIBC 2.35-0ubuntu3.1) 2.35

**Comment by mherger** [comment]
That should be fine. 

There's actually a discussion thread around this topic on https://forums.slimdevices.com/showthread.php?116395-LMS-Won-t-Start-on-Ubuntu-22-04. It basically confirms that 8.3 was working just fine.

BTW: your server.log.zip never arrived here. If you tried to send it using email, I think that's not working with Github. You'd have to use their web UI to attach the document.

**Comment by DaveInRedmond** [comment]
All’s well and LMS is up and running again like it used to after reading/applying the link you sent.

 

Much thanx for the help and I now know to send any future attachments thru the github UI rather than email.
